'use client';

import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, House, LayoutDashboard, Menu, PlugZap, Settings, ShieldCheck, Signal, SlidersHorizontal, Sun, TrendingUp, Wifi, X, Zap } from 'lucide-react';
import { duration, PowerState, recentEvents, segments, states, summary, time, weeklyChart } from '@/lib/demo';

const navigation = [{ name: 'Overview', icon: LayoutDashboard }, { name: 'Power history', icon: Clock3 }, { name: 'Insights', icon: TrendingUp }, { name: 'Devices', icon: PlugZap }];
type Modal = 'notifications' | 'help' | 'settings' | null;
export default function Dashboard() {
  const [page, setPage] = useState('Overview');
  const [period, setPeriod] = useState<'today' | 'week'>('today');
  const [power, setPower] = useState<PowerState>('ON');
  const [selectedDay, setSelectedDay] = useState(6);
  const [filter, setFilter] = useState('ALL');
  const [modal, setModal] = useState<Modal>(null);
  const [menu, setMenu] = useState(false);
  const [toast, setToast] = useState('');
  const [homeName, setHomeName] = useState('My home');
  const [alerts, setAlerts] = useState(true);
  const dialog = useRef<HTMLDialogElement>(null);
  const state = states[power], metrics = summary(period);
  useEffect(() => { try { setHomeName(localStorage.getItem('lt-home') || 'My home'); setAlerts(localStorage.getItem('lt-alerts') !== 'false'); } catch {} }, []);
  useEffect(() => { if (modal) dialog.current?.showModal(); else dialog.current?.close(); }, [modal]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 3500); return () => clearTimeout(id); }, [toast]);
  function go(name: string) { setPage(name); setMenu(false); }
  function exportCSV() {
    const rows = [['date', 'grid_on_hours', 'grid_off_hours', 'unknown_hours', 'availability_percent', 'coverage_percent'], ...weeklyChart.days.map(d => [d.date, d.gridOnHours, d.gridOffHours, d.unknownHours, d.availabilityPercent.toFixed(1), d.coveragePercent.toFixed(1)])];
    const url = URL.createObjectURL(new Blob([rows.map(r => r.join(',')).join('\n')], { type: 'text/csv;charset=utf-8;' }));
    const a = document.createElement('a'); a.href = url; a.download = 'light-tracker-demo-week-2026-09-05.csv'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 10000); setToast('Demo weekly report download started.');
  }
  function health(expanded = false) { return <section className={`panel health ${expanded ? 'expanded' : ''}`}>
    <div className="panel-heading"><div><h2>Tracker health</h2><p>A second sensor. A clearer picture.</p></div><span className={`tiny-badge ${power === 'ON' ? 'green' : 'amber'}`}>{power === 'ON' ? 'All good' : 'Check status'}</span></div>
    {[{ name: 'Grid sensor', detail: 'Sensor A · Grid-only socket', online: state.grid, icon: PlugZap }, { name: 'Backup sensor', detail: 'Sensor B · Inverter / UPS', online: state.backup, icon: Wifi }].map(s => <div className="sensor" key={s.name}><span className="sensor-icon"><s.icon size={21}/></span><div><h3>{s.name}</h3><p>{s.detail}</p></div><span className={`sensor-state ${s.online ? 'green-text' : 'muted'}`}><i className={s.online ? 'dot' : 'dot offline'}/>{s.online ? 'Online' : 'Offline'}</span></div>)}
    <div className="health-note"><ShieldCheck size={17}/><span>{power === 'ON' ? 'Both sensors checked at 18:00 WAT' : state.description}</span></div>
    {expanded && <div className="device-explainer"><h3>Why two sensors?</h3><p>The grid sensor checks your grid-only socket. The backup sensor checks your inverter or UPS and confirms that the internet is working. Keep your router connected to backup power.</p><p>Both offline means UNKNOWN. Grid online with backup offline means a setup fault. Neither is silently counted as an outage.</p></div>}
  </section>; }
  function events(full = false) { const list = recentEvents.events.filter(e => !full || filter === 'ALL' || e.state === filter); return <section className="panel events">
    <div className="panel-heading"><div><h2>{full ? 'Power history' : 'Recent activity'}</h2><p>Your home’s power, one moment at a time.</p></div>{!full && <button className="text-button" onClick={() => go('Power history')}>View all <ArrowRight size={15}/></button>}</div>
    {full && <div className="filter-row">{['ALL','ON','OFF','UNKNOWN'].map(f => <button key={f} onClick={() => setFilter(f)} className={filter === f ? 'selected' : ''}>{f === 'ALL' ? 'All events' : f === 'ON' ? 'Grid on' : f === 'OFF' ? 'Outages' : 'Unknown'}</button>)}</div>}
    <div className="event-table"><div className="event-row table-label"><span>EVENT</span><span>TIME (WAT)</span><span>DURATION</span></div>{list.slice(0, full ? 20 : 3).map((e, i) => <div className="event-row" key={e.id}><div className="event-name"><span className={`event-icon ${e.state.toLowerCase()}`}>{e.state === 'ON' ? <Zap size={15}/> : e.state === 'OFF' ? <PlugZap size={15}/> : <Wifi size={15}/>}</span><span><strong>{e.state === 'ON' ? 'Grid power restored' : e.state === 'OFF' ? 'Grid outage detected' : 'Connection lost'}</strong><small>{e.state === 'UNKNOWN' ? 'Unconfirmed · not counted as outage' : 'Confirmed by your sensors'}</small></span></div><span>{time(e.recordedAt)}</span><span>{duration(e.durationSeconds)}{i === 0 && (!full || filter === 'ALL') && <small className="ongoing">ongoing at snapshot</small>}</span></div>)}</div>
  </section>; }
  function chart() { const d = weeklyChart.days[selectedDay]; return <section className="panel weekly">
    <div className="panel-heading"><div><h2>Your week, in light</h2><p>Grid availability over the last 7 days</p></div><span className="chart-date">30 Aug – 5 Sep <ChevronDown size={13}/></span></div>
    <div className="chart-legend"><span><i className="legend-dot on"/>Grid on</span><span><i className="legend-dot off"/>Grid off</span><span><i className="legend-dot unknown"/>Unknown</span></div>
    <div className="bar-chart"><div className="y-axis"><span>24h</span><span>18h</span><span>12h</span><span>6h</span><span>0h</span></div><div className="plot"><div className="grid-lines"><i/><i/><i/><i/><i/></div>{weeklyChart.days.map((day, i) => <button key={day.date} onClick={() => setSelectedDay(i)} className={`bar-column ${selectedDay === i ? 'active' : ''}`} aria-label={`${day.date}: ${day.gridOnHours} hours on, ${day.gridOffHours} hours off, ${day.unknownHours} hours unknown. Select for details.`} aria-pressed={selectedDay === i}><div className="bar-stack"><span className="bar on" style={{ height: `${day.gridOnHours / 24 * 100}%` }}/><span className="bar off" style={{ height: `${day.gridOffHours / 24 * 100}%` }}/><span className="bar unknown" style={{ height: `${day.unknownHours / 24 * 100}%` }}/></div><span className="day-label">{['Sun','Mon','Tue','Wed','Thu','Fri','Today'][i]}</span></button>)}</div></div>
    <div className="chart-detail" aria-live="polite"><span><strong>{selectedDay === 6 ? 'Today' : ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday'][selectedDay]}</strong> · {duration(d.gridOnHours * 3600)} of grid power</span><span>{d.availabilityPercent.toFixed(1)}% availability <span className="detail-divider">/</span> {d.coveragePercent.toFixed(1)}% coverage</span></div>
  </section>; }
  return <div className="app-shell">
    {menu && <button aria-label="Close navigation" className="mobile-scrim" onClick={() => setMenu(false)}/>}
    <aside className={`sidebar ${menu ? 'open' : ''}`}><a className="brand" href="/" aria-label="Light Tracker home"><span className="brand-mark"><Zap size={23} fill="currentColor"/></span>light<span className="brand-light">tracker</span><span className="brand-period">.</span></a>
      <div className="workspace-label">YOUR WORKSPACE</div>
      <button className="home-switch" onClick={() => setModal('settings')}><span className="home-icon"><House size={19}/></span><span><strong>{homeName}</strong><small>Yaba, Lagos</small></span><ChevronDown size={15}/></button>
      <nav aria-label="Main navigation">{navigation.map(item => <button key={item.name} className={`nav-item ${page === item.name ? 'active' : ''}`} onClick={() => go(item.name)}><item.icon size={19}/>{item.name}{item.name === 'Devices' && <span className="nav-count">2</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="peace-card"><span className="peace-icon"><Sun size={23}/></span><h3>A little clarity.<br/>A little peace of mind.</h3><p>Know your power.<br/>Plan your day.</p><span className="peace-decoration"/></div><button className="nav-item" onClick={() => setModal('help')}><CircleHelp size={19}/>Help & how it works<ArrowUpRight size={15}/></button><button className="nav-item" onClick={() => setModal('settings')}><Settings size={19}/>Settings</button><div className="profile"><span className="avatar">AD</span><span><strong>Alex D.</strong><small>Pilot household</small></span><span className="pilot-tag">PILOT</span></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMenu(true)}><Menu size={20}/></button><House size={15}/><span>/</span><span>{page}</span></div><div className="topbar-right"><span className="demo-pill"><i/>Demo workspace</span><span className="topbar-separator"/><button className="icon-button notification-button" aria-label="View notifications" onClick={() => setModal('notifications')}><Bell size={19}/><i/></button><button className="avatar small-avatar" aria-label="Open profile settings" onClick={() => setModal('settings')}>AD</button></div></header>
    <main id="main-content"><div className="page-heading"><div className="greeting"><span>YOUR HOME, AT A GLANCE</span><h1>{page === 'Overview' ? 'Every hour of light counts.' : page === 'Insights' ? 'Get to know your power.' : page === 'Devices' ? 'Connected. And accounted for.' : 'The story behind the switch.'}</h1><p>{page === 'Overview' ? 'A clearer picture of your power. Less guesswork, more peace of mind.' : page === 'Insights' ? 'Understand the patterns, with confidence in the numbers.' : page === 'Devices' ? 'Two small sensors working together to give you the full picture.' : 'Confirmed changes and honest gaps, all in one place.'}</p></div><button className="button export" onClick={exportCSV}><ArrowDownToLine size={16}/>Export report</button></div>
    <div className="dashboard-toolbar">{(page === 'Overview' || page === 'Insights') && <div className="period-control" aria-label="Summary period"><button aria-pressed={period === 'today'} className={period === 'today' ? 'selected' : ''} onClick={() => setPeriod('today')}>Today</button><button aria-pressed={period === 'week'} className={period === 'week' ? 'selected' : ''} onClick={() => setPeriod('week')}>This week</button></div>}<span className="date-label"><Clock3 size={14}/>{period === 'today' || page === 'Power history' || page === 'Devices' ? 'Saturday, 5 September 2026' : '30 August – 5 September 2026'}<span className="wat">WAT</span></span></div>
    {page === 'Overview' && <><div className="status-layout"><section className={`status-card state-${power.toLowerCase()}`}><div className="status-content"><span className="status-eyebrow"><i/>{state.label.toUpperCase()}</span><h2>{state.title}</h2><p>{state.description}</p><div className="status-bottom"><span><Clock3 size={15}/>{power === 'ON' ? 'On for 4h 00m' : 'Scenario preview'}</span><span className="confidence"><ShieldCheck size={14}/>{state.confidence.toLowerCase()} confidence</span></div></div><div className="power-orbit"><div className="orbit outer"/><div className="orbit inner"/><div className="power-symbol"><Zap size={47} strokeWidth={1.7} fill="currentColor"/></div><span className="orbit-dot"/></div><div className="status-footer"><span><i/>Demo snapshot · 18:00 WAT</span><span>Two-sensor verification <ShieldCheck size={13}/></span></div></section><section className="panel coverage-card"><div className="coverage-heading"><span className="coverage-icon"><ShieldCheck size={20}/></span><span>Data you can trust</span><button className="icon-button" aria-label="How coverage is calculated" onClick={() => setModal('help')}><CircleHelp size={16}/></button></div><div className="coverage-number">{metrics.coveragePercent.toFixed(1)}<span>%</span><span className="tiny-badge green">High coverage</span></div><p>of {period === 'today' ? 'today' : 'this week'} successfully observed</p><div className="coverage-track"><span style={{ width: `${metrics.coveragePercent}%` }}/></div><div className="coverage-caption"><span><i className="legend-dot on"/>Confirmed</span><span>{duration(metrics.unknownSeconds)} unknown</span></div><div className="coverage-note">Unknown time is never counted as an outage.</div></section></div></>}
    {(page === 'Overview' || page === 'Insights') && <><div className="metrics-row"><Metric icon={<Zap size={18}/>} label="Grid power" value={duration(metrics.gridOnSeconds)} note={period === 'today' ? 'Of 18 hours elapsed today' : 'Across the last 7 days'} color="green"/><Metric icon={<PlugZap size={18}/>} label="Without grid power" value={duration(metrics.gridOffSeconds)} note="Confirmed outages only" color="red"/><Metric icon={<Activity size={18}/>} label="Grid availability" value={`${metrics.availabilityPercent.toFixed(1)}%`} note="Of confirmed observed time" color="green"/><Metric icon={<Signal size={18}/>} label={period === 'today' ? 'Outages today' : 'Data coverage'} value={period === 'today' ? '2' : `${metrics.coveragePercent.toFixed(1)}%`} note={period === 'today' ? 'Longest outage: 2h 00m' : 'Unknown time excluded'} color="amber"/></div>
    {page === 'Overview' && <section className="panel timeline"><div className="panel-heading"><div><h2>Today’s power rhythm</h2><p>The on, the off, and the in-between.</p></div><div className="chart-legend"><span><i className="legend-dot on"/>Grid on</span><span><i className="legend-dot off"/>Grid off</span><span><i className="legend-dot unknown"/>Unknown</span></div></div><div className="timeline-track">{segments.map((s, i) => <button key={i} className={`timeline-segment ${s.state.toLowerCase()}`} style={{ width: `${(s.end - s.start) / 24 * 100}%` }} onClick={() => setToast(`${s.state === 'ON' ? 'Grid on' : s.state === 'OFF' ? 'Grid off' : 'Unknown'} · ${duration(s.start * 3600)}–${duration(s.end * 3600)} WAT · ${duration((s.end - s.start) * 3600)}`)} aria-label={`${s.state} from ${s.start} to ${s.end} WAT`} title={`${s.state}: ${String(Math.floor(s.start)).padStart(2, '0')}:${s.start % 1 ? '30' : '00'}–${String(Math.floor(s.end)).padStart(2, '0')}:${s.end % 1 ? '30' : '00'} WAT`}/>) }<span className="future-time"/></div><div className="timeline-axis">{['00:00','04:00','08:00','12:00','16:00','20:00','24:00'].map(t => <span key={t}>{t}</span>)}</div></section>}
    <div className="chart-layout">{chart()}<section className="insight-card"><div className="insight-kicker"><span><Sun size={18}/></span>THE BRIGHT SIDE</div><h2>Your power.<br/>In perspective.</h2><p>You’ve had <strong>{duration(summary('week').gridOnSeconds)} of grid power</strong> this week. Wednesday was your brightest day, with 18 hours of light.</p><div className="insight-stat"><span>Weekly availability</span><strong>{summary('week').availabilityPercent.toFixed(1)}% <TrendingUp size={19}/></strong></div><button onClick={() => page === 'Insights' ? setModal('help') : go('Insights')}>{page === 'Insights' ? 'Understand the numbers' : 'Explore your insights'}<ArrowRight size={17}/></button><div className="insight-lines"/></section></div>
    {page === 'Overview' && <div className="bottom-layout">{events()}{health()}</div>}</>}
    {page === 'Power history' && <>{events(true)}<div className="honesty-note"><ShieldCheck size={19}/><p>All times are in West Africa Time (UTC+1). This history is a fixed demo snapshot; the scenario selector previews current status without rewriting historical events.</p></div></>}
    {page === 'Devices' && <div className="devices-layout">{health(true)}<section className="panel device-explainer"><h2>Try the two-sensor logic</h2><p>Use the demo controls below to see how each combination changes your home’s status.</p>{(Object.keys(states) as PowerState[]).map(s => <button className={`scenario-option ${power === s ? 'chosen' : ''}`} key={s} onClick={() => setPower(s)}><span><strong>{states[s].label}</strong><small>Grid {states[s].grid ? 'online' : 'offline'} · Backup {states[s].backup ? 'online' : 'offline'}</small></span>{power === s ? <Check size={18}/> : <ArrowRight size={18}/>}</button>)}</section></div>}
    <div className="demo-controls"><div><SlidersHorizontal size={16}/><span><strong>Take it for a spin</strong><span className="demo-hint"> · Preview a power state</span></span></div><div className="scenario-buttons">{(Object.keys(states) as PowerState[]).map(s => <button aria-pressed={power === s} className={power === s ? 'active' : ''} key={s} onClick={() => { setPower(s); if (page !== 'Overview' && page !== 'Devices') go('Overview'); }}>{s === 'ON' ? 'Grid on' : s === 'OFF' ? 'Grid off' : s === 'UNKNOWN' ? 'Unknown' : 'Setup fault'}</button>)}</div></div>
    <footer className="footer"><span><span className="footer-bolt">ϟ</span> Built for the way we live.</span><span>Lagos, Nigeria <span className="footer-dot">·</span> All times in WAT <span className="nigeria-flag">▌▐</span></span></footer>
    </main></div>
    <dialog aria-labelledby="dialog-title" ref={dialog} onCancel={() => setModal(null)} onClick={e => { if (e.target === e.currentTarget) setModal(null); }}><div className="dialog-heading"><span className="dialog-icon">{modal === 'settings' ? <Settings/> : modal === 'help' ? <ShieldCheck/> : <Bell/>}</span><button className="icon-button" aria-label="Close dialog" onClick={() => setModal(null)}><X size={21}/></button></div>
      <h2 id="dialog-title">{modal === 'settings' ? 'Make yourself at home.' : modal === 'help' ? 'Clarity, without the guesswork.' : 'You’re all caught up.'}</h2>
      {modal === 'settings' ? <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get('home')).trim() || 'My home'; setHomeName(name); try { localStorage.setItem('lt-home', name); localStorage.setItem('lt-alerts', String(alerts)); } catch {} setModal(null); setToast('Workspace preferences saved in this browser.'); }}><p>Personalize this demo workspace. Preferences stay in this browser.</p><label className="input-label" htmlFor="home-name">Home name</label><input id="home-name" name="home" defaultValue={homeName} maxLength={32} required/><label className="toggle-row"><span><strong>Power alerts preview</strong><small>Save your preference for future notifications.</small></span><input type="checkbox" checked={alerts} onChange={e => setAlerts(e.target.checked)}/></label><p className="form-note">Notifications and account services will be connected by the backend team.</p><button className="button primary" type="submit">Save preferences <Check size={16}/></button></form> : modal === 'help' ? <div className="help-copy"><p>Two sensors help distinguish a power outage from a connection problem.</p><div><strong>Availability = ON ÷ (ON + OFF)</strong><p>How much of your confirmed observed time had grid power.</p></div><div><strong>Coverage = (ON + OFF) ÷ elapsed time</strong><p>How much time we could confidently observe. Unknown time stays separate.</p></div><div><strong>This is a frontend prototype</strong><p>All readings are sample data, frozen at 18:00 WAT on 5 September 2026. State controls demonstrate sensor logic; they don’t change the historical report.</p></div></div> : <div className="notification-list"><div><span className="event-icon on"><Zap size={19}/></span><span><strong>Grid power restored</strong><p>Your grid came back at 14:00 WAT.</p><small>Demo · 5 September 2026</small></span></div><div><span className="event-icon unknown"><Wifi size={19}/></span><span><strong>A connection gap, not an outage</strong><p>Both sensors were unreachable from 10:00 to 10:30. This time is marked unknown.</p><small>Demo · 5 September 2026</small></span></div></div>}
    </dialog>{toast && <div className="toast" role="status"><Check size={17}/>{toast}<button aria-label="Dismiss message" onClick={() => setToast('')}><X size={15}/></button></div>}
  </div>;
}
function Metric({ icon, label, value, note, color }: { icon: React.ReactNode; label: string; value: string; note: string; color: string }) { return <section className="panel metric"><div className="metric-label">{label}<span className={`metric-icon ${color}`}>{icon}</span></div><strong className="metric-value">{value}</strong><p>{note}</p></section>; }


